# Generated by Django 4.2.6 on 2023-10-15 22:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_course_options_alter_coursecategory_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="address",
            new_name="skills",
        ),
    ]
