# Generated by Django 4.2.6 on 2023-10-16 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_rename_address_teacher_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="skills",
            new_name="Skills",
        ),
    ]
