# Generated by Django 4.2.2 on 2023-10-17 20:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_rename_skills_teacher_skills"),
    ]

    operations = [
        migrations.RenameField(
            model_name="teacher",
            old_name="Skills",
            new_name="skills",
        ),
    ]
