# Generated by Django 4.2.2 on 2023-10-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_rename_skills_teacher_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="featured_img",
            field=models.ImageField(null=True, upload_to="course_imgs/"),
        ),
        migrations.AddField(
            model_name="course",
            name="techs",
            field=models.TextField(null=True),
        ),
    ]
