# Generated by Django 4.2.2 on 2023-10-18 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_course_featured_img_course_techs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Teacher",
            new_name="teacher",
        ),
    ]
